# Generated by Django 4.1.1 on 2022-09-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('screen_no', models.IntegerField()),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_age', models.IntegerField()),
                ('user_phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.moviedetails')),
            ],
        ),
        migrations.CreateModel(
            name='SeatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('seat_status', models.BooleanField()),
                ('seat_price', models.IntegerField()),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.show')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.userdetails')),
            ],
        ),
    ]
