# Generated by Django 4.1.1 on 2022-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='moviepath',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
