# Generated by Django 4.1.1 on 2022-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_admindetails_moviedetails_moviepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='show',
            name='start_time',
        ),
        migrations.AddField(
            model_name='show',
            name='show_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
