# Generated by Django 4.1.1 on 2022-09-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_remove_show_end_time_remove_show_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
