# Generated by Django 4.1.1 on 2022-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_show_show_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatdetails',
            name='seat_price',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='seat_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
