# Generated by Django 4.1.1 on 2022-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_seatdetails_seat_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='moviepath',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='image',
            field=models.ImageField(default='slide-1.jpg', null=True, upload_to='img/'),
        ),
    ]
