# Generated by Django 4.1.1 on 2022-09-17 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_remove_moviedetails_moviepath_moviedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatdetails',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.userdetails'),
        ),
    ]
